### ISSUE TITLE
Possible improvement of the search functionality

### ISSUE THREAD

**Issue by ovizii** [thlucas1/spotifyplus_card#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Say I go to the search tab, it is set to search for artists. I enter the search term say "shaggy" and hit enter. 
I see the search results for shaggy within the artists. 

Long pressing or right-clicking a result apparently shows me top track by the artists or something along those lines. 

Say I now decide I want a playlist based on this artist or the Spotify radio for this artist, I need to select playlist in the drop-down then enter the search box again and hit enter.

### Describe the solution you'd like

How about one of these 2 solutions:

A) when long-pressing on a search result (artist) offer a click: “find playlist by artist” which automatically does a search for playlists with the same keyword used for the artist search

B) While displaying the search results OR the screen after long-pressing on a search result and I select “playlist” from the drop-down, automatically perform the search for the previously searched for search term

### Describe alternatives you've considered

Thanks for considering the feasibility of these suggested solutions.

### Additional context

Thanks for considering the feasibility of these suggested solutions.

**Comment by thlucas1** [comment]
@ovizii 
v1.0.10 will add this functionality.

Here's what it will look like ... did a search Artist for "shaggy", then a long press on the tile to display details / actions.  The new 3 dots "..." dropdown menu next to the artist favorite icon contains the search (and more) options for the artist:
![image](https://github.com/user-attachments/assets/f9058f2b-d74b-4036-bb10-38993e98eeae)


[ 1.0.10 ] - 2024/11/03

  * This release requires the SpotifyPlus v1.0.64 release; please make sure you update the SpotifyPlus integration prior to updating this SpotifyPlus Card release.
  * Added `footerIconSize` general config option to change the size of the footer area icons.
  * Added `playerControlsIconSize` player controls config option to change the size of the player control area icons, volume mute icon, and power on/off icons.
  * Added actions dropdown menu to all section favorites browser details; most of these are the ability to search for related details.  More actions to come in future releases.
  * Added actions dropdown menu to all player information details; most of these are the ability to search for related details.  More actions to come in future releases.
  * Added ability to copy device details to the clipboard; for example, click on the value next to the `Device ID` title to copy the device id to the clipboard.
  * Added (all browsers) action: copy Spotify URI to clipboard.
  * Added playlist action: recover playlists via Spotify web ui.
  * Added playlist action: delete (unfollow) a playlist.
  * Updated playlist item action: track will now be added to the play queue instead of being played.  This will avoid wiping out the play queue.
  * Updated album item action: track will now be added to the play queue instead of being played.  This will avoid wiping out the play queue.
  * Updated podcast show item action: episode will now be added to the play queue instead of being played.  This will avoid wiping out the play queue.
  * Updated audiobook item action: chapter will now be added to the play queue instead of being played.  This will avoid wiping out the play queue.

**Comment by thlucas1** [comment]
FYI - just released a new version of the [SpotifyPlus Card UI](https://github.com/thlucas1/spotifyplus_card/wiki) that should satisfy this enhancement requirement.  Please verify, and let me know if it does not.  Thanks!

[ 1.0.10 ] - 2024/11/03

- This release requires the SpotifyPlus v1.0.64 release; please make sure you update the SpotifyPlus integration prior to updating this SpotifyPlus Card release.
- Added footerIconSize general config option to change the size of the footer area icons.
- Added playerControlsIconSize player controls config option to change the size of the player control area icons, volume mute icon, and power on/off icons.
- Added actions dropdown menu to all section favorites browser details; most of these are the ability to search for related details. More actions to come in future releases.
- Added actions dropdown menu to all player information details; most of these are the ability to search for related details. More actions to come in future releases.
- Added ability to copy device details to the clipboard; for example, click on the value next to the Device ID title to copy the device id to the clipboard.
- Added (all browsers) action: copy Spotify URI to clipboard.
- Added playlist action: recover playlists via Spotify web ui.
- Added playlist action: delete (unfollow) a playlist.
- Updated playlist item action: track will now be added to the play queue instead of being played. This will avoid wiping out the play queue.
- Updated album item action: track will now be added to the play queue instead of being played. This will avoid wiping out the play queue.
- Updated podcast show item action: episode will now be added to the play queue instead of being played. This will avoid wiping out the play queue.
- Updated audiobook item action: chapter will now be added to the play queue instead of being played. This will avoid wiping out the play queue.

**Comment by ovizii** [comment]
Excellent. I'm very happy with the improvements. Thank you so much for constantly making this card better. I only have one improvement suggestion left:

After searching for an artist, how about also having the option to search for all his albums?

![image](https://github.com/user-attachments/assets/9960d29e-fa4e-43ef-8295-167f5b145fdb)



Btw. I'm also very happy about these changes:

```
Updated playlist item action: track will now be added to the play queue instead of being played. This will avoid wiping out the play queue.
Updated album item action: track will now be added to the play queue instead of being played. This will avoid wiping out the play queue.
```

Oh, btw. waht does "recover playlist" do?

![image](https://github.com/user-attachments/assets/19d95060-00a9-4452-b616-54ebe4c11afa)

**Comment by thlucas1** [comment]
_Oh, btw. waht does "recover playlist" do?_
The “Recover Playlist” action opens a new web browser tab window to the Spotify playlist  recovery tool.  It allows you to recover your playlist(s) that you have deleted / unfollowed.  This only works for playlists that you created (not other users playlists).

_After searching for an artist, how about also having the option to search for all his albums?_
The artist albums list us displayed under the artist image and details.  Though I see your point, as the album list does not contain cover images.  I can add an action to drive you to the search form for that.

I am also planning a couple of other search artist actions that allow you to search for their top tracks as well as related artists.  That’s in the works, and will be available with a future release.

Thanks for all of your help with this.

**Comment by ovizii** [comment]
> _After searching for an artist, how about also having the option to search for all his albums?_
> The artist albums list us displayed under the artist image and details. Though I see your point, as the album list does not contain cover images. I can add an action to drive you to the search form for that.

Oh, I see, I thought it was showing tracks, not albums :-( I totally ignored the column specifying the type of album :-)

Now I realized the rationale of “search for artist albums” seeing that it leads to an overview with covers. Looks great.
