### ISSUE TITLE
Can not select device unless admin user

### ISSUE THREAD

**Issue by gary-sargent** [thlucas1/spotifyplus_card#26]
## System Information

version | core-2024.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1463
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 2 September 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | [redacted]
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 229.2 GB
disk_used | 18.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), Log Viewer (0.17.1), Network UPS Tools (0.13.2), ESPHome (2024.9.2), Terminal & SSH (9.15.0), Advanced SSH & Web Terminal (19.0.0), Mosquitto broker (6.4.1), texecom2mqtt (1.2.3), OpenThread Border Router (2.12.0), Matter Server (6.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 13
-- | --
resources | 11
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 November 2024 at 16:16
-- | --
current_recorder_run | 20 November 2024 at 12:02
estimated_db_size | 954.87 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>SpotifyPlus</summary>

integration_version | v1.0.65
-- | --
clients_configured | 1: [redacted] (premium)
api_endpoint_reachable | ok

</details>

### Checklist

- [X] I am running the latest version of Home Assistant for my installation.
- [X] I am running the latest version of the card.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Bug%22+).

### Describe the issue

When logged in as a non-admin user, I am unable to select a device in the spotify card.

### Reproduction Steps

1. Create non-admin user
2. View dashboard with spotifyplus card on it
3. Click the devices button

Expected: List of devices shown
Actual: Error message says "Get Spotify Connect Devices failed: Unauthorized"

### Debug / Console Logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:315
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20 November 2024 at 21:19:46 (7 occurrences)
Last logged: 11:12:57

[546483354448] Error handling message: Unauthorized (unauthorized) Shelly Wall Display Upstairs Landing from 192.168.123.148 (ShellyStargate/2.3.0-dd2e06a3-beta3; SAWD-0A1XX10EU1)
```

**Comment by thlucas1** [comment]
@gary-sargent 
Hi Gary - I am setting up a non-admin account to test this.  Do you know if you have the "local access only" checked for the non-admin account?

**Comment by gary-sargent** [comment]
> @gary-sargent Hi Gary - I am setting up a non-admin account to test this. Do you know if you have the "local access only" checked for the non-admin account?

I do have "local access only" checked, but I also tried a different non-admin account that doesn't and got the same.

**Comment by thlucas1** [comment]
Ok, thank you.  
I don't think it's the integration that's causing this, but want to make sure.  I always run it (and my testing) on an admin account, so it will be a good test.  Will keep you posted.  
Thanks - Todd

**Comment by thlucas1** [comment]
Wow!  I am getting the same "Unauthorized" message for almost every section display!
The only functions that work are the Player display, and the user-preset browser.
I will research this some more, and get back to you.
Thank you for bringing this to my attention.

**Comment by thlucas1** [comment]
Bad news, I am afraid ...

It appears that Home Assistant limits the access to calls made to the `execute_script` service to Adminstrator accounts only.  The following shows up in the system logs when a non-admin account tries to call `execute_script`:
```
2024-11-21 09:05:30.953 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139636436972400] Error handling message: Unauthorized (unauthorized) TestUser 1 NoAdmin from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36)
```

The SpotifyPlus Card makes calls to `execute_script` to call services provided by the SpotifyPlus integration that return service response data.  This is basically for any of the browser sections that display data.  For example, the SpotifyPlus Card calls the SpotifyPlus integration `get_spotify_connect_devices` service to return data about Spotify Connect devices available on the local network.  This fails, because it has to call the `get_spotify_connect_devices` service via a call to `execute_script`, which knows how to handle service response data. 

The SpotifyPlus Card player commands work fine, since they are just commands (e.g. play, pause, next track, volume change, etc) and do not return service response data (e.g. no call to `execute_script`, as the services are called directly).  The SpotifyPlus Card user-preset browser works fine, since it reads preset data from the configuration and the local file system (e.g. no service required).

Unfortunately, there is nothing I can do at this point to fix this as Home Assistant core does not provide a way to call a service directly that returns service response data.  A call to `execute_script` must be made to call the service via a script, which then returns the service response data.

I will make some inquiries out on the developer Discord forums, but I have little hope that they will be addressed anytime soon.

**Comment by gary-sargent** [comment]
I agree it seems by design. Is there not some other way you can call the services provided by the SpotifyPlus integration? Could that integration provide its own endpoint that the card could use?

**Comment by thlucas1** [comment]
There is no other way that I know of to call an HA integration service that returns service response data.  It would be a complete re-write of the Card if to interface with the Spotify Web API endpoints, and it would also drop Sonos support (which is built into the SpotifyPlus integration).  To be up front, that option is a no-go for me.

What's really odd is that the HA Core developers introduced service response data in the July 2023 release, but they didn't give us a way to call a service directly and return it's response data.  It all has to be done in automation logic or in a script.

I have an email out to Allen Porter, who was the force behind adding the service response data support.  I have also posted on the Discord Developer forum with the same question.

I also added an [Install Instructions Limitations](https://github.com/thlucas1/spotifyplus_card/wiki/Installation-Instructions#limitations) section to the wiki docs with the non-administrator notes.

Again, I have little hope that they will be addressed anytime soon though.

**Comment by thlucas1** [comment]
And the following was the response from Allen Porter:
```
On Friday, November 22, 2024 at 12:08:10 AM CST, Allen Porter <xxxxxx@xxxxx.com> wrote:
Hi,
Please don't email for support and stick to the existing support channels. (I hear you that you didn't get a reply.)Thanks!
```

**Comment by gary-sargent** [comment]
Could the card take an alternative user to use for the execute_script calls instead of using the logged in user? Could a long lived access token be created and configured in the card settings? https://developers.home-assistant.io/docs/auth_api/

**Comment by thlucas1** [comment]
Access tokens are geared toward web / REST services, of which the SpotifyPlus does not use.  AFAIK, there is no way to specify a surrogate / alternate user-id on a call made to the `hass.connection.sendMessagePromise` method.

However, I did see some docs about Permissions in the link you provided that looks promising.  As with most things Home Assistant related, there is no good examples on how to setup permissions so I am going to have to do some digging / experimenting.  It looks promising though - will keep you posted.

**Comment by thlucas1** [comment]
Good news, and I am an idiot sometimes!  LOL

It turns out responses were added to `call_service` endpoint in November of 2023, four months after (I believe) service response data was introduced.  In that time, I had to use the `sendMessagePromise` with `execute_script` to return service response data as I was one of the early adopters to handle service response data in my integrations.  I did not realize the `call_service` endpoint was updated to accommodate response data.

The `call_service` endpoint supports calls for non-administrators.  I am finishing up some testing, and will get this released later on today.

Thanks for bringing this to my attention.

**Comment by gary-sargent** [comment]
That's great news @thlucas1 nice one!

**Comment by thlucas1** [comment]
FYI - just released a new version of the [SpotifyPlus Card Dashboard](https://github.com/thlucas1/spotifyplus_card/wiki)

This should fix the non-administrator access issue.  Please give it a try when you get a chance and let me know.
I will leave the issue open in case it does not, and close it later if I have not heard back from you.

Thanks again for bringing this to my attention.

[ 1.0.14 ] - 2024/11/25

  * Non-Administrator accounts can now use the card without receiving the `unauthorized` message.  Note that non-administrators cannot change the card configuration (as designed).
  * Changed the way calls are made to the underlying SpotifyPlus integration services.  Calls are now made using the `hass.callService` method instead of the `hass.connection.sendMessagePromise` with type `execute_script`.  This was causing all calls that returned service response data to fail with `unauthorized` errors.

**Comment by gary-sargent** [comment]
Works great! Thanks for the super quick turn-around!

Do you have an account on https://buymeacoffee.com/ or similar?

**Comment by thlucas1** [comment]
You're welcome - glad it's working.
Here's my [Buy me a Coffee account link](https://www.buymeacoffee.com/thlucas1) - I appreciate it if you want to buy me a slice, thank you!

**Comment by steveguitar78** [comment]
All works fine! I had the same issue. Now is ok with new release. Thank you so much

**Comment by thlucas1** [comment]
Closing this issue, as it appears it is resolved.  Feel free to reopen if needed.
Thanks - Todd
