### ISSUE TITLE
Player improvement

### ISSUE THREAD

**Issue by SofaSurfer76** [thlucas1/spotifyplus_card#34]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It's actually no problem

### Describe the solution you'd like

I would like, if possible, to improve the experience with the player with these requests, it's actually more than one:
- Add playlist name in main Playing section, as info
- Add “LIKE/(+) BUTTON” in the Play/next... section of the player, to add the track to favorites/followed track 
- Inside the Playlist or Album, Artist tracklist’s section , when clicking on the track, instead of play just that track (so a tracklist with 1 element), start to play the tracklist from that one, like it happens in the mobile Spotify app
- back button pressed go back to beginning if time from track begin is < 2-3 secs, else go to previous track. Now it goes directly to previous track

### Describe alternatives you've considered

Use the player as it is. 

### Additional context

no screenshot

**Comment by thlucas1** [comment]
### _Add playlist name in main Playing section, as info_
You can use the following [title formatter options](https://github.com/thlucas1/spotifyplus_card/wiki/Configuration-Options#title-formatter-options) to add the playlist name (and many other things) to the main playing section.  See the link above for all of the available options.
- `{player.sp_playlist_name}` Playlist name being played, if the current context is a playlist (e.g. "DJ").
- `{player.sp_playlist_name_title}` Playlist name being played along with surrounding parenthesis (e.g. "(My Playlist Name)", if the current context is a playlist.
Like so:
![image](https://github.com/user-attachments/assets/68268f04-17dc-468c-a599-62e483de87db)

### _Add “LIKE/(+) BUTTON” in the Play/next... section of the player, to add the track to favorites/followed track_
This will be available in the next release.

### _Inside the Playlist or Album, Artist tracklist’s section , when clicking on the track, instead of play just that track (so a tracklist with 1 element), start to play the tracklist from that one, like it happens in the mobile Spotify app_
I can probably get this added in the next release.

### _Back button pressed go back to beginning if time from track begin is < 2-3 secs, else go to previous track.  Now it goes directly to previous track_
This will be available in the next release.

**Comment by thlucas1** [comment]
### _Inside the Playlist or Album, Artist tracklist’s section , when clicking on the track, instead of play just that track (so a tracklist with 1 element), start to play the tracklist from that one, like it happens in the mobile Spotify app_

This behavior was changed in the latest version of the card to add the selected item to the play queue (instead of playing the track immediately).  Based on the behavior that I have observed with the Spotify desktop player, it will play queue items immediately after the current song ends, then resume play in the selected playlist.  Can you verify that you have the latest card version installed?

Note that the older version of the card simply started playing the selected track and stopping play after that.

**Comment by thlucas1** [comment]
Released v1.0.19 of the card.

[ 1.0.19 ] - 2024/12/15

  * Added favorite indicator to the player section form for track, show episode, and audiobook items.  The heart icon will be displayed to the right of the item name.  A solid red heart indicates the item is a favorite; a transparent heart indicates the item is not a favorite.
  * Added "Play All Track Favorites" action to the track favorites section actions.  This will get a list of the tracks saved in the current Spotify user's 'Your Library' and starts playing them, with shuffle enabled..
  * Added logic to player `PREVIOUS_TRACK` control so that if more than 8 seconds have passed the currently playing track is just restarted from the beginning; otherwise, the previous track is selected if progress is past the 8 second point.

**Comment by thlucas1** [comment]
Request complete.

**Comment by SofaSurfer76** [comment]
Sorry but I have been very busy in the last weeks and didn't play much with the card, I will check the requests.
Happy holidays!
